name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: [self-hosted, linux, x64, runner-class-cac]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
